3825 Order projects in API responses
this-andy/thiscovery-core pull request #163
Opened 2022-01-20 09:26 UTC by sophiemachin

The order of project statuses should be:
- testing
- active:
  - any projects that have testing tasks 
  - any projects with active tasks
  - projects with all tasks complete
- completed

The order of task statuses should be:
- testing 
- chronological order

2022-01-21 13:12 UTC, afs25 requested changes
The ordering of projects appears to be correct, but more work is needed to order the tasks within projects (testing tasks are not first in the list; I haven't checked if completed tasks are at the end).

2022-01-21 13:13 UTC, sophiemachin commented on api/tests/test_scripts/unit_tests/test_project.py
> +                PROJECT_07_JSON,
Ah yeah good spot. They hadn't changed from the previous sorting, which was alphabetical.

2022-01-21 17:09 UTC, sophiemachin commented on api/endpoints/project.py
> +                            tasks = [task] + tasks
Now using two separate lists so this point is moot

2022-01-24 13:41 UTC, afs25 approved these changes

2022-01-24 13:47 UTC, merged